version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./back-end
    ports:
      - "3001:3001"
    volumes:
      - ./back-end:/usr/src/app

  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/usr/src/app
    depends_on:
      - backend
